#### 전주 데이터셋 확인

In [32]:
import numpy as np
import pandas as pd
from freeman.aiddd.data_manager import read_data

In [3]:
%%time
df_data = read_data('2nd provide pole')
df_data.shape

CPU times: user 17.2 s, sys: 40 ms, total: 17.2 s
Wall time: 17.2 s

(38390, 63)

In [4]:
# 한개의 값으로 구성된 컬럼 제거
nunique_per_column = df_data.nunique()
single_value_column_list = nunique_per_column[nunique_per_column == 1].index
df_data.drop(columns=single_value_column_list, axis=1, inplace=True)

# 결과확인
print(
    f'Number of Drop Columns: {len(single_value_column_list)}\n'
    f'Columns: {[col for col in single_value_column_list]}\n'
    f'Data shape: {df_data.shape}'
)

Number of Drop Columns: 16
Columns: ['공사변경순번', '공사구분코드', '공사성격코드', '전주수량', '도색판공사특성코드', '전주버팀목공사특성코드', '철주철탑중량', '각입중량', '잔토처리여부', '기설설비유실여부', '선로순시여부', '조류둥지철거여부', '아라미드공법여부', '선로순시횟수', '조류둥지철거수량', '고강도전주_영업배전_공사성격']
Data shape: (38390, 47)

In [5]:
for _column_name in df_data.columns:
    print(df_data[_column_name].value_counts().sort_values(ascending=False))

공사번호
476920213694    106
477420193177    100
477420193089     55
442720203885     51
476920204407     48
               ...
477420213335      1
474620225316      1
474620225259      1
477420213327      1
474620234659      1
Name: count, Length: 18313, dtype: int64
전산화번호
6304S412    2
6787D042    1
7298B392    1
7298B422    1
7298B441    1
           ..
4000Q262    1
3496F851    1
3801A842    1
3302X561    1
3899W931    1
Name: count, Length: 38389, dtype: int64
GISID
262913093    1
262913073    1
262913071    1
262913099    1
262913083    1
            ..
401866975    1
405460980    1
409085086    1
405727377    1
405998316    1
Name: count, Length: 38390, dtype: int64
전주순번
0    38389
1        1
Name: count, dtype: int64
전주형태코드
O    37068
G     1194
V      121
H        7
Name: count, dtype: int64
전주종류코드
C    29998
H     7744
B      468
E       28
1       19
M        4
R        3
2        2
Q        2
Name: count, dtype: int64
전주규격코드
10.0    21448
12.0     7312
16.0     6412
14.0     2623
6.0       468
11.0        3
8.0         1
20.0        1
Name: count, dtype: int64
도색판종류코드
C    21079
Z    17106
T      204
S        1
Name: count, dtype: int64
전주버팀목수량
1    36789
0     1068
2      533
Name: count, dtype: int64
번호판구분코드
P    37349
D      767
S       89
G       31
Name: count, dtype: int64
Series([], Name: count, dtype: int64)
암반율코드
0.0     706
30.0    159
50.0     42
80.0     23
99.0      5
Name: count, dtype: int64
부수기종류코드
C    20
Z     7
T     6
A     1
Name: count, dtype: int64
부수기량
0.0    38364
0.3        7
0.5        7
2.0        6
0.1        5
0.4        1
Name: count, dtype: int64
Series([], Name: count, dtype: int64)
Series([], Name: count, dtype: int64)
암반종류코드
N    157
K      7
Y      1
Name: count, dtype: int64
풍속
32    37684
35      535
10       61
20       32
30       22
43       17
15       13
23        7
34        5
1         4
25        4
44        1
5         1
6         1
0         1
2         1
28        1
Name: count, dtype: int64
지반코드
A    38378
B       11
Name: count, dtype: int64
전주깊이
1.7    21448
2.0     7312
2.5     6382
2.4     2622
0.0      591
2.8       28
1.9        3
2.7        1
1.4        1
3.2        1
2.6        1
Name: count, dtype: int64
점용위치코드
F    8466
S    7199
P    6708
W    4719
K    4399
R    3230
Y    1458
N    1024
J     969
G     215
Z       2
Name: count, dtype: int64
점용구분코드
E    24577
J    12712
N      319
L      307
Y      291
K      120
W       46
R       16
Name: count, dtype: int64
Series([], Name: count, dtype: int64)
Series([], Name: count, dtype: int64)
Series([], Name: count, dtype: int64)
Series([], Name: count, dtype: int64)
전주종류명세코드
AA2    12
5       5
NA2     3
AB2     2
B       2
ND3     1
NB2     1
Name: count, dtype: int64
점용위치구분코드
P    24919
N    13469
Name: count, dtype: int64
전주버팀목종류코드
M     14124
H     12688
K      4200
L      3791
A      2519
ZZ      370
Name: count, dtype: int64
Series([], Name: count, dtype: int64)
추가밑둥묻기깊이
0     38378
50        5
30        3
20        1
40        1
70        1
10        1
Name: count, dtype: int64
Series([], Name: count, dtype: int64)
최초등록일시
2022-02-08 10:34:34    106
2023-05-08 22:24:50    100
2020-12-04 18:33:32     55
2021-10-29 16:46:57     51
2021-03-11 16:25:29     48
                      ...
2022-01-12 13:25:22      1
2022-01-04 09:14:51      1
2022-01-24 14:04:50      1
2022-01-10 07:53:38      1
2023-07-19 14:05:56      1
Name: count, Length: 18306, dtype: int64
최초등록자사번
mda1570558    1726
mdp2100146    1679
mdp2100006    1662
mde1900018    1596
mde1900005    1580
              ...
mde1505463       1
mde1704136       1
2015105461       1
mdp2213756       1
2013105880       1
Name: count, Length: 214, dtype: int64
최종변경일시
2022-02-08 10:34:34    106
2023-05-08 22:24:50    100
2020-12-04 18:33:32     55
2021-10-29 16:46:57     51
2021-03-11 16:25:29     48
                      ...
2022-01-12 13:25:22      1
2022-01-04 09:14:51      1
2022-01-24 14:04:50      1
2022-01-10 07:53:38      1
2023-07-19 14:05:56      1
Name: count, Length: 18306, dtype: int64
최종변경자사번
mda1570558    1726
mdp2100146    1679
mdp2100006    1662
mde1900018    1596
mde1900005    1580
              ...
mde1505463       1
mde1704136       1
2015105461       1
mdp2213756       1
2013105880       1
Name: count, Length: 214, dtype: int64
Series([], Name: count, dtype: int64)
Series([], Name: count, dtype: int64)
고강도전주사용유무
N    34878
Y     3512
Name: count, dtype: int64
Series([], Name: count, dtype: int64)
사업소명
증평괴산지사    5555
동청주지사     4340
영동지사      3821
보은지사      3815
충주지사      3813
제천지사      3280
음성지사      3020
단양지사      2811
충북본부직할    2697
옥천지사      2631
진천지사      2607
Name: count, dtype: int64
접수종류코드
11    32556
1C     4095
22      543
21      328
28      294
23      234
18      116
29      113
26       50
14       38
24       17
25        6
Name: count, dtype: int64
접수종류명
신설(상용/임시)     32556
신설(발전기)        4095
공급방식변경증설        543
증설              328
단순공급방식변경        294
계약종별변경증설        234
해지후재사용(신규)      116
공급지점변경          113
계약단위합병           50
신증설(예비전력)        38
일부해지(신규)         17
계약단위분할            6
Name: count, dtype: int64
공사형태코드
2    38092
3      231
1       67
Name: count, dtype: int64
공사형태명
외선소요         38092
외선소요(선공급)      231
외선불요            67
Name: count, dtype: int64
계약전력
3      15064
5      10729
4       1738
100     1099
10      1077
       ...
380        1
990        1
181        1
449        1
196        1
Name: count, Length: 270, dtype: int64
X좌표-Y좌표
14289801.7912967,4449034.10434287,1,0    1
14289935.5327959,4448486.93889943,1,0    1
14289918.1267563,4448426.89915652,1,0    1
14289779.4326686,4449247.65154221,1,0    1
14289866.3975293,4448813.21423375,1,0    1
                                        ..
14237353.2124476,4452605.53959219,1,0    1
14223890.2030581,4443852.17927242,1,0    1
14232137.0741798,4456313.9969829,1,0     1
14221317.4204539,4457753.95391433,1,0    1
14233402.7568735,4449946.86057668,1,0    1
Name: count, Length: 38390, dtype: int64

#### 질문사항:
* `전주형태코드`는 지형지물이나 기타 지리적 요건으로 자동 지정이 가능한가?
* `전주종류코드`는 지형지물이나 기타 지리적 요건으로 자동 지정이 가능한가?
* `전주규격코드`는 지형지물이나 거리 등 지리적 요건으로 자동 지정이 가능한가?
* `전주버팀목수량`은 경로상의 전주간 각도 등으로 추정 가능한가?
* `전주버팀목종류코드`는 경로상의 전주간 각도 등으로 추정 가능한가?
* `암반율코드`는 지형지물이나 기타 지리적 요건으로 자동 지정이 가능한가?
* `암반종류코드`는 지형지물이나 기타 지리적 요건으로 자동 지정이 가능한가?
* `풍속`은 어떤값을 지정하나? 자동으로 지정할 수 있나? 해당 지역의 년평균풍속이라든지?
* `지반코드`는 지형지물이나 기타 지리적 요건으로 자동 지정이 가능한가?
* `전주깊이`는 지형지물이나 기타 지리적 요건으로 자동 지정이 가능한가?
* `점용위치코드`는 지형지물이나 기타 지리적 요건으로 자동 지정이 가능한가?
* `점용구분코드`는 지형지물이나 기타 지리적 요건으로 자동 지정이 가능한가?
* `고강도전주사용유무`는 지형지물이나 기타 지리적 요건으로 자동 지정이 가능한가?

#### 전산화번호

In [6]:
df_data[df_data['전산화번호']=='6304S412']

,공사번호,전산화번호,GISID,전주순번,전주형태코드,전주종류코드,전주규격코드,도색판종류코드,전주버팀목수량,번호판구분코드,...,H빔공사성격코드,고강도전주사용유무,전주오름볼트사용여부,사업소명,접수종류코드,접수종류명,공사형태코드,공사형태명,계약전력,X좌표-Y좌표
21494,474920213231,6304S412,343215190,0,O,C,10.0,C,1,P,...,NaN,N,NaN,제천지사,11,신설(상용/임시),2,외선소요,3,"14267172.175975,4461824.25581191,1,0"
21925,474920213966,6304S412,351541314,0,O,C,10.0,C,1,P,...,NaN,N,NaN,제천지사,11,신설(상용/임시),2,외선소요,5,"14267214.0920556,4461787.72958481,1,0"

In [8]:
df_data_no_442720203885 = df_data[df_data['공사번호']=='442720203885']

In [10]:
df_data_xy = df_data[['공사번호', '전산화번호', 'GISID', 'X좌표-Y좌표']]

In [11]:
df_data_xy.iloc[0]['X좌표-Y좌표']

'14289801.7912967,4449034.10434287,1,0'

In [13]:
df_data_xy = df_data_xy.copy()
df_data_xy[['x', 'y', 'one', 'zero']] = \
    df_data_xy['X좌표-Y좌표'].str.split(',', expand=True)

In [15]:
for _key in ['one', 'zero']:
    print(df_data_xy[_key].value_counts())

one
1    38390
Name: count, dtype: int64
zero
0    38390
Name: count, dtype: int64

In [16]:
df_data_xy_sorted = df_data_xy.copy()
df_data_xy_sorted = df_data_xy_sorted.sort_values(by=['공사번호', '전산화번호'])

In [19]:
_check_idx = 0
for _idx, _row in df_data_xy_sorted.iterrows():
    print(_idx, _row.values)
    if _check_idx > 3:
        break
    _check_idx += 1

2811 ['442720173009' '2274E946' 240001222
 '14193002.1108434,4388890.30222702,1,0' '14193002.1108434'
 '4388890.30222702' '1' '0']
2812 ['442720173009' '2275W532' 287818448
 '14192759.7965464,4390079.4163759,1,0' '14192759.7965464'
 '4390079.4163759' '1' '0']
2813 ['442720173009' '2275W541' 240558929
 '14192757.370998,4390092.38811853,1,0' '14192757.370998'
 '4390092.38811853' '1' '0']
2814 ['442720173009' '2275Y462' 264545249
 '14192706.7397098,4389631.09393951,1,0' '14192706.7397098'
 '4389631.09393951' '1' '0']
2815 ['442720173789' '3473Q202' 317322580
 '14221835.1393864,4384695.19306763,1,0' '14221835.1393864'
 '4384695.19306763' '1' '0']

In [24]:
# 전산화번호로 정렬된 상태에서
# 같은 공사번호인 경우 인덱스 순서가 다른(이전 인덱스가 현재 인덱스보다 큰) 레코드 확인
prev_const_no = 0
prev_index_no = 0
prev_row = None

check_result = []
for index, row in df_data_xy_sorted.iterrows():
    current_const_no = row['공사번호']
    if prev_const_no == current_const_no and index < prev_index_no:
        prev_values = [1, prev_index_no] + prev_row.values
        current_values = [2, index] + row.values
        check_result.append(prev_values)
        check_result.append(current_values)
    prev_const_no = current_const_no
    prev_index_no = index
    prev_row = row

* 전산화번호로 정렬한 경우 인덱스가 역전된 경우가 없는것을 보니 전산화번호순으로 전주 순서가 생성되는것 같음

#### GISID

In [25]:
df_data_xy_sorted = df_data_xy_sorted.sort_values(by=['공사번호', 'GISID'])

In [45]:
# GISID로 정렬된 상태에서
# 같은 공사번호인 경우 인덱스 순서가 다른(이전 인덱스가 현재 인덱스보다 큰) 레코드 확인
prev_const_no = 0
prev_index_no = 0
prev_row = None

check_result = []
for index, row in df_data_xy_sorted.iterrows():
    current_const_no = row['공사번호']
    if prev_const_no == current_const_no and index < prev_index_no:
        prev_values_head = np.array([1, prev_index_no])
        prev_values = [1, prev_index_no] + prev_row.values.tolist()
        # current_values_head = np.array([2, index])
        # current_values = np.concatenate((current_values_head, row.values), axis=None)
        current_values = [2, index] + row.values.tolist()
        check_result.append(prev_values)
        check_result.append(current_values)
    prev_const_no = current_const_no
    prev_index_no = index
    prev_row = row

In [46]:
column_names = ['순서', '인덱스'] + df_data_xy_sorted.columns.to_list()
df_check_result = pd.DataFrame(check_result, columns=column_names)

* GISID로는 인덱스가 일정하지 않음, 지도에 찍어봐야 알 수 있나?